language: erlang # wither art thou, Go?

before_install:
 - sudo service rabbitmq-server start
 - sudo tail -F /var/log/rabbitmq/* &
 - sudo rabbitmqctl add_vhost /                               || true
 - sudo rabbitmqctl add_user guest guest                      || true
 - sudo rabbitmqctl set_permissions -p / guest ".*" ".*" ".*" || true

install:
 - hg clone -r go1.0.2 https://code.google.com/p/go $HOME/go
 - cd $HOME/go/src && ./make.bash
 - mkdir -p $HOME/src || true
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - ln -s $HOME/builds/streadway/amqp $HOME/src/amqp

script:
 - sh -c "sleep 120 && killall -QUIT amqp.test" &
 - cd $HOME/src/amqp && go build -v .
 - cd $HOME/src/amqp && AMQP_URL=amqp://guest:guest@127.0.0.1:5672/ go test .

