name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Set up Go environment
      uses: actions/setup-go@v2
    - name: Tests
      run: AMQP_URL=amqp://guest:guest@localhost:5672/ go test -cpu=1,2 -v -tags integration
